apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore-app
  template:
    metadata:
      labels:
        app: aspnetcore-app
    spec:
      containers:
        - name: aspnetcore-container
          image: your-aspnet-core-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080  # تغییر به 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-service
spec:
  type: NodePort
  selector:
    app: aspnetcore-app
  ports:
    - protocol: TCP
      port: 8080  # تغییر به 8080
      targetPort: 8080  # تغییر به 8080
      nodePort: 30007  # پورت خارجی که در دسترس است
